version: '3'

services:
  odoo-17:
    image: kgisl-odoo:v3
    container_name: odoo
    volumes:
      - odooappdata:/var/lib/odoo
      - ./extra-odoo-addons:/mnt/extra-addons
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGHOST=db
      - PGUSER=odoo
      - PGPASSWORD=odoo

  db:
    image: postgres:16
    container_name: postgres
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - './odoo-db-dump:/resources/db-dump'
      - 'odoodbdata:/var/lib/postgresql/data'

volumes:
  odooappdata:
  odoodbdata:
